import { Student } from './types';

export const MOCK_STUDENTS: Student[] = [
  {
    id: '1',
    stt: 1,
    studentId: '079210922002',
    name: 'TRẦN THỊ BÌNH',
    group: 'Nhà trẻ',
    className: 'Chồi 2',
    bookId: null,
    status: 'pending_create',
  },
  {
    id: '2',
    stt: 2,
    studentId: '079211105007',
    name: 'ĐẶNG MINH TUẤN',
    group: 'Nhà trẻ',
    className: 'Chồi 2',
    bookId: null,
    status: 'pending_create',
  },
  {
    id: '3',
    stt: 3,
    studentId: '079211212015',
    name: 'PHẠM VIỆT HOÀNG',
    group: 'Nhà trẻ',
    className: 'Chồi 2',
    bookId: null,
    status: 'pending_create',
  },
  {
    id: '4',
    stt: 4,
    studentId: '079210810016',
    name: 'NGÔ BẢO CHÂU',
    group: 'Nhà trẻ',
    className: 'Chồi 2',
    bookId: null,
    status: 'pending_create',
  },
  {
    id: '5',
    stt: 5,
    studentId: '079220418009',
    name: 'PHAN THANH SƠN',
    group: 'Nhà trẻ',
    className: 'Mầm 3',
    bookId: null,
    status: 'pending_create',
  },
  {
    id: '6',
    stt: 6,
    studentId: '079220301013',
    name: 'TRỊNH QUỐC BẢO',
    group: 'Nhà trẻ',
    className: 'Mầm 3',
    bookId: null,
    status: 'pending_create',
  },
  {
    id: '7',
    stt: 7,
    studentId: '079201030010',
    name: 'ĐỖ GIA HÂN',
    group: 'Mẫu giáo',
    className: 'Lá 1',
    bookId: null,
    status: 'pending_create',
  },
  {
    id: '8',
    stt: 8,
    studentId: '079201111011',
    name: 'TRẦN GIA BẢO',
    group: 'Mẫu giáo',
    className: 'Lá 1',
    bookId: null,
    status: 'pending_create',
  },
  {
    id: '9',
    stt: 9,
    studentId: '079190101001',
    name: 'VÕ MINH KHANG',
    group: 'Mẫu giáo',
    className: 'Lá 3',
    bookId: null,
    status: 'pending_create',
  },
  {
    id: '10',
    stt: 10,
    studentId: '079190520002',
    name: 'ĐINH BẢO NGỌC',
    group: 'Mẫu giáo',
    className: 'Lá 3',
    bookId: null,
    status: 'pending_create',
  },
  {
    id: '11',
    stt: 11,
    studentId: '079190909003',
    name: 'LƯƠNG THẾ VINH',
    group: 'Mẫu giáo',
    className: 'Lá 3',
    bookId: null,
    status: 'pending_create',
  },
];
